# Generated by Django 4.0.6 on 2022-07-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_task_created_at_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 9, 27, 48, 171825)),
        ),
    ]
