# Generated by Django 4.0.6 on 2022-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='industry',
            field=models.CharField(default='EPL', max_length=200),
        ),
    ]
