# Generated by Django 4.0.6 on 2022-07-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0002_sponsor_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='industry',
            field=models.CharField(choices=[('CO', 'Textile'), ('BE', 'Beverages'), ('TE', 'Tech'), ('AV', 'Aviation'), ('FB', 'Football')], default='FB', max_length=2),
        ),
    ]
